import React from 'react';

export const MigrationRules = () => {
  return (
    <div className="migration-content">
      <h2 className="text-[#69d9e7] font-ethnocentric text-xl mb-4">
        APE SUI SOCIETY - MIGRATION RULES
      </h2>
      
      <p className="mb-4">1) THE MIGRATION WILL BEGIN ON <b>MARCH XX 2024 AT XX:XX UTC </b> AND <b>THE DEADLINE WILL BE AFTER 33 DAYS FROM THE START.</b></p>
      
      <p className="mb-4">2) IF YOU HAVE YOUR BORED APE SUI CLUB OR MUTANT APE SUI CLUB NFTs LISTED, DELIST THEM FROM THE MARKETPLACES TO MIGRATE TO APE SUI SOCIETY NFTs.</p>
      
      <p className="mb-4">3) APE SUI SOCIETY NFTs THAT WON'T BE MIGRATED BEFORE THE DEADLINE <b>WILL BE BURNED, OR USED FOR FUTURE PROMOTIONS & REWARDS TO THE COMMUNITY.</b></p>
      
      <p className="mb-4">ALL THE BORED APE SUI CLUB & MUTANT APE SUI CLUB NFTs THAT WON'T BE MIGRATED <b>WILL BE USELESS IN FUTURE AND WILL NOT RECEIVE ANY BENEFITS FROM FUTURE PROJECT DEVELOPMENTS (REWARDS, STAKING, AIRDROP, ETC...).</b></p>
      
      <p className="mb-4">5) IN ORDER TO MIGRATE YOU WILL NEED TO BURN YOUR BORED APE SUI CLUB OR MUTANT APE SUI CLUB NFTs WITHIN THIS WEBSITE.<br />
      <b>NFTS MUST BE BURNED ONLY THROUGH OUR DAPP.</b></p>
      
      <p>6) PRESS THE <b>"MIGRATE"</b> BUTTON TO BURN YOUR BASCs/MASCs. <b>THERE WILL BE A SMALL FEE OF 0.50 $SUI FOR EACH NFT YOU ARE GOING TO BURN.</b><br />
      AFTER DOING THE BURN YOU WILL AUTOMATICALLY RECEIVE THE NEW NFTs WITHIN FEW MINUTES DIRECTLY INTO YOUR WALLET.</p>
    </div>
  );
};